### PR TITLE
Support for uncalibrated gyroscope + refactoring

### PR DESCRIPTION
**Pull request by lrq3000**
Hey there,

As we discussed, I updated the code to support TYPE_GYROSCOPE_UNCALIBRATED (which is probably what the reddit user meant by TYPE_RAW_GYROSCOPE, but the latter doesn't exist).

I also refactored the code to use the new name.

BTW, I have found an opensource app called [GyroscopeExplorer](https://github.com/KEOpenSource/GyroscopeExplorer) which implements all kinds of gyroscope's filters, from the simple mean filter to advanced fusion filters with kalman. So that's a great source of info and code if we ever want to implement more advanced filters.

However, I tried the GyroscopeExplorer app (in fact I was already using it for my tests but without knowing that it was opensource nor that there was some advanced filtering available), and there's no filter inside that can avoid jitter. In fact, the filters are more useful to meet two goals:
1. Smooth transition from one angle to the next, smoothing the movement noise.
2. Get an absolute angle by eliminating the drift.

However, it does not prevent jitters, which is our app's main goal. So I decided not to spend too much time trying to implement those advanced filters since our app already works very well as it is for a wide array of apps.

But, the second goal (eliminating drift) could be very interesting, so it may be interesting to try to implement those advanced filters anyway to meet this goal, but I consider it secondary to jitter. So I added the link to the README.md in a ToDo section, if some future contributor ever wants to try to do that.

Next, I am going to submit the APK to the Xposed repo, I'll keep you updated :)

### CODE REVIEW

**Comment by Kjos** [comment]
The type_raw_gyroscope was how I had it memorized, bit off. I tried a gyro testing app once too, could have been the same one. I remember that the jitter occurred there as well.
Drift compensation is cool, but take into account that doing drift compensation twice doesn't work out well. Cardboard apps probably already do drift compensation in the newer versions.

**Comment by lrq3000** [comment]
I tried the app Cineveo, but it seems that now it's using TYPE_GYROSCOPE and not the uncalibrated because it didn't work if I tried to only anti-jitter the uncalibrated.

Yes you're right about drift compensation, so that's another reason to avoid working on that and focus more on the jitter.

Have you got an account on XDA? I can add your XDA account as a co-author so that you have the rights to modify the package there.

**Comment by Kjos** [comment]
Mmmm.. I think leaving the raw feature in is a good idea, but it does need testing with some app. I remember cartoon village having it in an older release at least. I heard it got removed later on.

I'll create an xda account maybe, but tbh I'm not missing out a lot not having one u til now. I remember signing up for one and becoming frustrated with their registration, but maybe that's changed.

**Comment by lrq3000** [comment]
Normally it should work the same with uncalibrated values, the only difference is that there's a fourth value in the provided float[] array but we don't use it anyway so it should work as expected. But anyway there is an issues tracker so if there's ever a problem, someone will notify us :)

I just created another XDA account with my current username, and it went very smoothly and quickly, so you shouldn't worry of your past issues anymore. If you register, tell me your username after having registered and I'll add you on the Xposed repo :)

For now please excuse me, I'm going to try to watch a full movie inside Cineveo without the jitters! ;)

**Comment by lrq3000** [comment]
Found an app that isn't supported by our module: Cmoar Cinema Pro. Weirdly, Cmoar Cinema Free is totally supported (that's what I've been using the most for my tests), but the Pro app is somehow bypassing the system hook you did.

That's the conclusion I came to, because I tried to totally nullify all sensors (I modified the module and I added a hook for every type possible, and then I have set a huge value for Minimum value change and Stationary value change, so that all sensors stay at 0). But then, even if all sensors are nullified (I checked with several apps that show the readout of the sensors), Cmoar Cinema Pro is the only app I have that can still somehow access the sensors! So it must somehow have a precedence over our module, but I can't understand how they did that.

If you have any idea to explore, I'm open to any suggestion, because right now I can't see what we can do.

**Comment by lrq3000** [comment]
Ok I think I have found the culprit using another, free, VR cinema app called VRTV Free: it's when the app uses the Cardboard SDK directly to manage the sensors.

I'm opening an issue => #4

**Pull request merged**
