### PR TITLE
Lots of new features (new filter types, rounding, threshold, etc.)

### PR DESCRIPTION
**Pull request by lrq3000**
Hi there,

In this PR, I fixed the minimum value change threshold option (it didn't work in my previous PR), plus I added lots of new options that are configurable on-the-fly from the options screen, so that one can tweak the options and see what fits best.

Could you please make an APK to distribute it? (maybe even make a release to keep a history of the previous original version you released and the new one)

### CODE REVIEW

**Comment by lrq3000** [comment]
PS: with the new options, I could tweak my gyroscope so that I don't have any jitter at all while having almost as much responsivity as without a filter (by using the lowpass filter, it's a lot more responsive than the others, and by using the stationary min change threshold and rounding). I don't think I will add new features from now on, unless you have some ideas of features.

**Comment by Kjos** [comment]
Cool stuff! 

I played with the hooking a while back, and that's one thing that might need improving. I notice some Cardboard games don't hook well (some Unity ones). I used to have an alternative hook into the Cardboard library, after which I decided to hook into the system directly.

Edit: Now that I think of it, it might be because these Unity games link to the NDK. This would be a little tricky to fix with Xposed.

By the way, are you using Lollipop, KitKat or something else entirely?

**Comment by lrq3000** [comment]
I'm using KitKat, and for the moment, the hook works for every games and
apps I have been using, so it seems to be good enough for most purposes.

BTW, I noticed there's no licensing for your module. Do you have an idea of
what license you would like to use? I am updating the readme right now.

2015-09-15 20:50 GMT+02:00 Kjos notifications@github.com:

**Comment by lrq3000** [comment]
About games that don't hook well, have you got an example?

I'm thinking I have indeed seen some games that seems to work less well
with the median filter, but that's just because these games were computing
their own filters and this was conflicting with the median filter, but now
we can choose the lowpass filter for example and it seems to never
conflicts with any game (since those games generally use some kind of
lowpass filter).

But in my case, the games were hooked anyway, it was just a conflict with
the filter, so maybe if you have an example of a game that can't be hooked
I can check it out?

2015-09-15 23:25 GMT+02:00 Stephen LARROQUE lrq3000@gmail.com:

**Comment by lrq3000** [comment]
About uploading to the Xposed repo, it's here, you just need to create/use
an XDA forum account:

http://repo.xposed.info/

Do you want to upload the module by yourself or would you prefer me to do
it (however if I do it, the author's name won't be yours, but I will add
you to the credit section as the main author of course).

2015-09-15 23:29 GMT+02:00 Stephen LARROQUE lrq3000@gmail.com:

**Comment by Kjos** [comment]
You agree with a GPLv2 license? That seems well suited for this application.

Can't recall which games I had trouble with unfortunately. I'm on Lollipop now, but I can check if I can get xposed running. Last time I checked it was unstable. Would be nice to see if the hook works too on Lollipop.

If you like, you can upload to the xposed repo. I've looked into it before briefly, but haven't gotten around to it. A credit mention to me would be kind and plenty.

**Comment by Kjos** [comment]
Don't think I can install Xposed on my phone :( Lots of bootloops around..

**Comment by Kjos** [comment]
Probably will try Cyanogenmod later on.

**Comment by lrq3000** [comment]
Ok for the license and everything, I'll notify you when it's uploaded to
the Xposed repo :)

I also posted an announcement on the XDA forums
http://forum.xda-developers.com/xposed/modules/mod-jitterygyrofixforcardboard-t3202149
.

About the bootloops, have you got a Samsung phone? If it's the case, there
are specific builds of Xposed that run around this issue. If you have
another phone, maybe you can try a search on this thread:
http://forum.xda-developers.com/showthread.php?t=3034811

2015-09-16 9:50 GMT+02:00 Kjos notifications@github.com:

**Comment by Kjos** [comment]
Okay, I'll add the GPLv2 license then.

I have a Moto G 2014 (2nd). I've watched the thread about this phone, but the problem is that Motorola has some custom code in Lollipop that doesn't always play nice with Xposed leading to bootloops for some users. I could try it, but I might as well just install Cyanogenmod then.
I reverted to KitKat a while back, which was nice, but at some point some software required Lollipop so I caved. I'm thinking about developing/playing a bit for Cardboard and the like again, so I have to find a way to get this module working again. I'm curious to try your improvements to :)

**Comment by Kjos** [comment]
https://www.reddit.com/r/GoogleCardboard/comments/335ins/fix_for_jittery_gyroscopes_such_as_moto_g/csenfab

This might be something that needs improving. Some apps use Sensor.TYPE_RAW_GYROSCOPE instead of Sensor.TYPE_GYROSCOPE. These will probably the apps that don't work yet. A simple addition to the if statement here

https://github.com/Kjos/JitteryGyroFixForCardboard/blob/master/SensorMedianFilter/src/net/kajos/median/MedianFilter.java#L173

would fix that. Maybe take into account that not all Android version have the TYPE_RAW_GYROSCOPE, by checking the Android version first.

**Comment by lrq3000** [comment]
Ah yes indeed if you have a motorola, it's always tricky (I used to own
only motorola phones...). Indeed if there's a CM Lollipop for your phone,
you should use that instead, it should worrk better.

Ok about TYPE_RAW_GYROSCOPE I'm going to add that, thank's for the feedback
:)

Also, since the module now includes a lot more than just the median filter,
would you be OK if I refactor the classes so that it's renamed to
"GyroscopeNoiseFilter" instead?

2015-09-16 13:15 GMT+02:00 Kjos notifications@github.com:

**Comment by lrq3000** [comment]
Also, about refactoring, normally it's best usage to not commit the bin/
and gen/ folders (these should be automatically generated on the end-user
env), but including them allows to more easily compile the first time
(particularly on Eclipse which can sometimes be tricky...).

Would you like me to remove those folders or keep them (currently what I do
is that I commit them in a separate commit to avoid mixing up code change
and binaries updates)?

2015-09-16 13:29 GMT+02:00 Stephen LARROQUE lrq3000@gmail.com:

**Comment by Kjos** [comment]
GyroscopeNoiseFilter is a better name indeed. Maybe change the package name and readme too, as I figure people might use this besides Cardboard purposes. I just renamed the Github too to broader terminology, so you know. Old link still works though.

I generally like it when people at least leave in the compiled binary, but the classes could be ignored. I don't mind personally either.

**Comment by Kjos** [comment]
About the renaming, I wouldn't bother too much if it's too much of a hassle.

**Comment by lrq3000** [comment]
No the refactoring it won't be bothering since it will kind of automatic
with Eclipse, but I will still try it out on my test phone just to check
that everything's ok :)

About the binaries, do you mean the APK or the full bin/ folder? Because we
can still provide the APK with each release, just like I did here:
https://github.com/lrq3000/JitteryGyroFixForCardboard/releases/tag/v1.3

Would this be OK for you or you prefer to keep the bin/ folder?

2015-09-16 13:54 GMT+02:00 Kjos notifications@github.com:

**Comment by Kjos** [comment]
Ah, that's fine too :+1:

**Comment by lrq3000** [comment]
Great, then I'll do these updates in a few hours :)

2015-09-16 15:38 GMT+02:00 Kjos notifications@github.com:

**Pull request merged**
