### PR TITLE
init ru

### PR DESCRIPTION
**Pull request by webserfer**

### CODE REVIEW

**Comment by Kjos** [comment]
What are these changes?

2016-04-20 0:49 GMT+02:00 Roman notifications@github.com:

**Comment by lrq3000** [comment]
Seems like they are for russian translation, am I correct?

**Comment by Kjos** [comment]
Ah, yes, you are. I didn't see any changes first I looked. I think it would
fit better for a fork or it would need a translation option, etc.

2016-04-20 23:20 GMT+02:00 Stephen L. notifications@github.com:

**Comment by lrq3000** [comment]
I think Android will automatically switch the language of the app depending
on the system settings, but maybe i'm wrong?

2016-04-20 23:23 GMT+02:00 Kjos notifications@github.com:

**Comment by Kjos** [comment]
Yeah, could very well be. I never played around with that, I don't really
know. Could be that Xposed handles it else.

2016-04-20 23:33 GMT+02:00 Stephen L. notifications@github.com:

**Pull request closed without merging**
